"""Add claim system models and extend bot model

Revision ID: 54385acfcc47
Revises: 
Create Date: 2026-02-08 01:51:21.177772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54385acfcc47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feishu_user_id', sa.String(length=128), nullable=False),
    sa.Column('feishu_open_id', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feishu_open_id')
    )
    op.create_index(op.f('ix_users_feishu_user_id'), 'users', ['feishu_user_id'], unique=True)
    op.create_table('bots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.String(length=255), nullable=False),
    sa.Column('bot_name', sa.String(length=255), nullable=False),
    sa.Column('feishu_app_id', sa.String(length=128), nullable=True),
    sa.Column('feishu_bot_id', sa.String(length=128), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('UNCLAIMED', 'CLAIMED', 'OFFLINE', 'ONLINE', 'BUSY', 'ERROR', name='botstatus'), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('claim_code', sa.String(length=64), nullable=True),
    sa.Column('claim_code_expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bots_bot_id'), 'bots', ['bot_id'], unique=True)
    op.create_index(op.f('ix_bots_claim_code'), 'bots', ['claim_code'], unique=True)
    op.create_index(op.f('ix_bots_feishu_app_id'), 'bots', ['feishu_app_id'], unique=False)
    op.create_index(op.f('ix_bots_owner_id'), 'bots', ['owner_id'], unique=False)
    op.create_table('bot_access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('access_type', sa.Enum('OWNER', 'HIRE', 'SHARE', name='claimtype'), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_access_grants_bot_id'), 'bot_access_grants', ['bot_id'], unique=False)
    op.create_index(op.f('ix_bot_access_grants_user_id'), 'bot_access_grants', ['user_id'], unique=False)
    op.create_table('claim_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bot_id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('claim_type', sa.Enum('OWNER', 'HIRE', 'SHARE', name='claimtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='claimstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('feishu_verified', sa.Boolean(), nullable=True),
    sa.Column('feishu_verification_data', sa.JSON(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approval_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_requests_bot_id'), 'claim_requests', ['bot_id'], unique=False)
    op.create_index(op.f('ix_claim_requests_requester_id'), 'claim_requests', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_requests_requester_id'), table_name='claim_requests')
    op.drop_index(op.f('ix_claim_requests_bot_id'), table_name='claim_requests')
    op.drop_table('claim_requests')
    op.drop_index(op.f('ix_bot_access_grants_user_id'), table_name='bot_access_grants')
    op.drop_index(op.f('ix_bot_access_grants_bot_id'), table_name='bot_access_grants')
    op.drop_table('bot_access_grants')
    op.drop_index(op.f('ix_bots_owner_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_feishu_app_id'), table_name='bots')
    op.drop_index(op.f('ix_bots_claim_code'), table_name='bots')
    op.drop_index(op.f('ix_bots_bot_id'), table_name='bots')
    op.drop_table('bots')
    op.drop_index(op.f('ix_users_feishu_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
